propID
time NORMAL
time TIME_CRITICAL
instrument
PI
email
isntitution
title
abstract
coIs name
coIs last name
coIs email

In [47]:
import pandas as pd

In [56]:
noirlab_all_file = 'programs noirlab complete.xlsx'
noirlab_all = pd.read_excel(noirlab_all_file,sheet_name=None)
noirlab_1 = noirlab_all['All EG proposals']
noirlab_2 = noirlab_all['Sheet 1 - Proposal-Export_BsA99']

noirlab_aeon_file = 'programs noirlab to schedule.csv'
noirlab_aeon = pd.read_csv(noirlab_aeon_file)

chile_all_file = 'CNTAC 2026B SOAR allocation.xlsx - Sheet1.csv'
chile_all_file = pd.read_csv(chile_all_file)

In [57]:
# Define your list of columns
cols = [
    'propID',
    'time NORMAL',
    'time TIME_CRITICAL',
    'instrument',
    'PI',
    'email',
    'isntitution',
    'title',
    'abstract',
    'coIs name',
    'coIs last name',
    'coIs email'
]

# Create the empty DataFrame
df = pd.DataFrame(columns=cols)

# Display the structure to verify
print(df.head())

Empty DataFrame
Columns: [propID, time NORMAL, time TIME_CRITICAL, instrument, PI, email, isntitution, title, abstract, coIs name, coIs last name, coIs email]
Index: []

In [58]:
# noirlab

cond = (noirlab_aeon['Instrument'] == 'Goodman') | (noirlab_aeon['Instrument'] == 'TripleSpec4.1')
noirlab_aeon = noirlab_aeon[cond]

cond = noirlab_aeon['Scheduling Constraints'].str.contains('AQ', na=False)
noirlab_aeon = noirlab_aeon[cond]

noirlab_aeon['Propid'] = noirlab_aeon['Propid'].str.replace(r'^N', '2026B-', regex=True)
noirlab_aeon['Propid'] = noirlab_aeon['Propid'].str.replace(r'^25B', '2025B', regex=True)
noirlab_aeon

,Key,Propid,PI,Instrument,Req,Sched,Phase,Opt,Acc,Scheduling Constraints
0,S722,2025B-366722,Blanchard,Goodman,5.0,0.0,NaN,NaN,NaN,AQ: Survey.
1,S422,2025B-589422,Sand,Goodman,0.7,0.0,NaN,NaN,NaN,AQ: Survey.
2,S282,2025B-886282,Hosseinzadeh,Goodman,5.0,0.0,NaN,NaN,NaN,AQ: Survey.
7,N682,2026B-607682,Panda,TripleSpec4.1,2.7,0.0,NaN,NaN,NaN,AQ: bright
9,N372,2026B-214372,Ogrady-Rose,TripleSpec4.1,1.0,0.0,NaN,NaN,NaN,AQ: bright
10,N927,2026B-174927,Rackham,TripleSpec4.1,1.4,0.0,NaN,NaN,NaN,AQ: bright
12,N123,2026B-987123,Panda,Goodman,2.6,0.0,NaN,NaN,NaN,AQ: Gray
16,N681,2026B-819681,Fremling-Hinds,Goodman,2.0,0.0,NaN,NaN,NaN,AQ: Gray
17,N833,2026B-458833,Ould-rouis,Goodman,1.1,0.0,NaN,NaN,NaN,AQ: Dark
20,N708,2026B-341708,Rehemtulla,Goodman,1.6,0.0,NaN,NaN,NaN,AQ: Gray
22,N088,2026B-942088,Bellm,Goodman,0.8,0.0,NaN,NaN,NaN,AQ: Gray
23,N854,2026B-532854,Townsend,Goodman,1.2,0.0,NaN,NaN,NaN,AQ: Dark
26,N429,2026B-904429,Liu,Goodman,0.7,0.0,NaN,NaN,NaN,AQ: Gray
28,N798,2026B-731798,Gordon,Goodman,1.0,0.0,NaN,NaN,NaN,AQ: bright
29,N365,2026B-398365,Davis,Goodman,1.5,0.0,NaN,NaN,NaN,AQ (1n)+ToO (0.5n)
30,N126,2026B-352126,Panda,Goodman,5.6,0.0,NaN,NaN,NaN,AQ: Gray
31,N718,2026B-531718,Perkins,Goodman,1.0,0.0,NaN,NaN,NaN,AQ: Dark
32,N664,2026B-431664,Hinkle,Goodman,0.9,0.0,NaN,NaN,NaN,AQ: Gray
33,N013,2026B-891013,Boutsia,Goodman,2.0,0.0,NaN,NaN,NaN,AQ: Bright

In [59]:
 # ToO : Davis, Hosseinzadeh, Sand
# give more time to surveys 
# 2025B-366722	Blanchard	5 goodman
# 2025B-589422	Sand	0.7 goodman
# 2025B-886282	Hosseinzadeh   5 goodman

In [61]:
combined_df = pd.concat([noirlab_1, noirlab_2], ignore_index=True)

In [71]:
import pandas as pd

# 1. Define the columns you want to pull from noirlab_all 
# (You must include 'number_long' so pandas knows what to match on)
cols_to_pull = [
    'number_long', 'title', 'abstract', 
    'pi_names', 'pi_emails', 'coi_names', 'coi_emails'
]

# 2. Merge the dataframes
noirlab_aeon_updated = pd.merge(
    noirlab_aeon,
    combined_df[cols_to_pull], 
    left_on='Propid', 
    right_on='number_long', 
    how='left'
)

# Optional: Drop the 'number_long' column if you don't want it repeating 
# what's already in the 'Propid' column
noirlab_aeon_updated = noirlab_aeon_updated.drop(columns=['Key','number_long','Sched','Phase','Opt','Acc'])
noirlab_aeon_updated = noirlab_aeon_updated.drop_duplicates()

noirlab_aeon_updated['Sand']

In [72]:
noirlab_aeon_updated

,Propid,PI,Instrument,Req,Scheduling Constraints,title,abstract,pi_names,pi_emails,coi_names,coi_emails
0,2025B-366722,Blanchard,Goodman,5.0,AQ: Survey.,NaN,NaN,NaN,NaN,NaN,NaN
1,2025B-589422,Sand,Goodman,0.7,AQ: Survey.,NaN,NaN,NaN,NaN,NaN,NaN
2,2025B-886282,Hosseinzadeh,Goodman,5.0,AQ: Survey.,NaN,NaN,NaN,NaN,NaN,NaN
3,2026B-607682,Panda,TripleSpec4.1,2.7,AQ: bright,A NIR Spectroscopic Study of Bright AGN Backup...,The broad-line region (BLR) encodes the fundam...,Swayamtrupta Panda,swayamtrupta.panda@noirlab.edu,"Anahis De la barra manzano, Yan-rong Li, Mary ...",ADELABARRA2020@udec.cl; liyanrong@mail.ihep.ac...
5,2026B-214372,Ogrady-Rose,TripleSpec4.1,1.0,AQ: bright,Searching for super-AGB stars in the Magellani...,Super-asymptotic giant branch (SAGB) stars rep...,"Anna O'grady, Sam Rose",aogrady@andrew.cmu.edu; srose@caltech.edu,"Kaustav Das, Kishalay De, Maria Drout, Daichi ...",kdas@caltech.edu; kd3038@columbia.edu; maria.d...
6,2026B-174927,Rackham,TripleSpec4.1,1.4,AQ: bright,Characterizing Cool Candidate Exoplanet Hosts ...,Planetary transits of cool dwarfs (T_eff < 390...,Benjamin Rackham,brackham@mit.edu,Adam Burgasser,aburgasser@ucsd.edu
7,2026B-987123,Panda,Goodman,2.6,AQ: Gray,Radio-mode AGN feedback caught in the act,We have selected a sample of 14 nearby radio g...,Swayamtrupta Panda,swayamtrupta.panda@noirlab.edu,"Edi Bon, Miroslav Filipovic, Paola Marziani",edibon@gmail.com; M.Filipovic@westernsydney.ed...
9,2026B-819681,Fremling-Hinds,Goodman,2.0,AQ: Gray,Supporting Z+LIONS: ZTF+LSST Inventory Of Nucl...,The Vera Rubin Observatory's LSST will discove...,"Christoffer Fremling, K-ryan Hinds",fremling@caltech.edu; khinds@caltech.edu,"Igor Andreoni, Ryan Chornock, Michael Coughlin...",igor.andreoni@unc.edu; chornock@berkeley.edu; ...
11,2026B-458833,Ould-rouis,Goodman,1.1,AQ: Dark,Searching for the remnants of the most massive...,Intermediate-mass main sequence stars are diﬃc...,Lou baya Ould rouis,lbor@bu.edu,"Joseph Guidry, Jj Hermes",jaguidry@bu.edu; jjhermes@bu.edu
12,2026B-341708,Rehemtulla,Goodman,1.6,AQ: Gray,Surveying infant supernovae by automatically t...,Despite great advances in our understanding of...,Nabeel Rehemtulla,nabeelr@u.northwestern.edu,"Igor Andreoni, Jonathan Carney, Michael Coughl...",igor.andreoni@unc.edu; jcarney@unc.edu; cough0...
14,2026B-942088,Bellm,Goodman,0.8,AQ: Gray,Characterizing the Accretion Disks of Compact ...,The Vera C. Rubin Observatory is now beginning...,Eric Bellm,ecbellm@uw.edu,"Poshak Gandhi, Rob Hynes, Liliana Rivera sandoval",poshak.gandhi@soton.ac.uk; rhynes@lsu.edu; lil...
16,2026B-532854,Townsend,Goodman,1.2,AQ: Dark,Spectroscopic Classification of Strongly Lense...,Strong gravitationally lensed supernovae are n...,Alice Townsend,a.townsend@bham.ac.uk,"Suhail Dhawan, Ariel Goobar, Erin Hayes, Joel ...",s.dhawan@bham.ac.uk; ariel@fysik.su.se; eeh55@...
18,2026B-904429,Liu,Goodman,0.7,AQ: Gray,A Systematic Study of the Coolest Explosions,"Red, subluminous transients are one of the rem...",Chang Liu,ptg.cliu@u.northwestern.edu,"Georgios Dimitriadis, Saarah Hall, Lindsey Kwo...",g.dimitriadis@lancaster.ac.uk; saarah@u.northw...
20,2026B-731798,Gordon,Goodman,1.0,AQ: bright,Constructing a Complete Sample of Fast Radio B...,"Fast radio bursts (FRBs) are bright, milliseco...",Alexa Gordon,alexagordon2026@u.northwestern.edu,"Lucas Bernales, Manisha Caleb, Adam Deller, Yu...",lucas.bernales.c@mail.pucv.cl; manisha.caleb@s...
22,2026B-398365,Davis,Goodman,1.5,AQ (1n)+ToO (0.5n),Flux-limited characterization of GRBs and othe...,"We propose a flux-limited, duration-agnostic f...",Michael Davis,davi4614@umn.edu,"Tomas Ahumada, Shreya Anand, Michael Coughlin,...",tomas.ahumada@noirlab.edu; sanand08@stanford.e...
24,2026B-352126,Panda,Goodman,5.6,AQ: Gray,Assessing the reliability of Single-Band Photo...,The reverberation mapping (RM) method measures...,Swayamtrupta Panda,swayamtrupta.panda@noirlab.edu,Szymon Kozlowski,simkoz@astrouw.edu.pl
26,2026B-531718,Perkins,Goodman,1.0,AQ: Dark,Exploring the Physics of Early-Times Rare Tran...,The imminent arrival of wide-field surveys lik...,Haille Perkins,haillep2@illinois.edu,"Henna Abunemeh, Katie Auchettl, Kyle Davis, Ka...",habun2@illinois.edu; katie.auchettl@unimelb.ed...
28,2026B-431664,Hinkle,Goodman,0.9,AQ: Gray,Building an ANT-hill: SOAR/AEON Optical Spectr...,All massive galaxies host supermassive black h...,Jason Hinkle,jhinkle6@illinois.edu,"Katie Auchettl, Athena Engholm, Decker French,...",katie.auchettl@unimelb.edu.au; engholm2@illino...
30,2026B-891013,Boutsia,Goodman,2.0,AQ: Bright,Populating the redshift desert,"Bright, high-z QSOs are of fundamental importa...",Konstantina Boutsia,konstantina.boutsia@noirlab.edu,"Giorgio Calderone, Stefano Cristiani, Andrea G...",giorgio.calderone@inaf.it; stefano.cristiani@i...

In [70]:
noirlab_aeon_updated.keys()

Index(['Key', 'Propid', 'PI', 'Instrument', 'Req', 'Scheduling Constraints',
       'title', 'abstract', 'pi_names', 'pi_emails', 'coi_names',
       'coi_emails'],
      dtype='str')

In [85]:
# noirlab programs
# 1. Map your existing column names to your desired new names
# Note: I mapped 'pi_names' to 'PI_name', but if you prefer the 'PI' column, 
# just change 'pi_names' to 'PI' in the dictionary below.
column_mapping = {
    'Propid': 'PropID',
    'pi_names': 'PI_name',      
    'pi_emails': 'PI_email',
    'title': 'Title',
    'abstract': 'Abstract',
    'coi_names': 'coIs_name',
    'coi_emails': 'coIs_email',
    'Req': 'time NORMAL'
    # 'Instrument' doesn't need mapping since the name isn't changing
}

# 2. Rename the columns in a new DataFrame
new_df = noirlab_aeon_updated.rename(columns=column_mapping)

# 3. Define the exact final list and order of columns you want
target_columns = [
    'PropID', 'time TIME_CRITICAL', 'time NORMAL', 'Instrument',
    'PI_name', 'PI_email', 'PI_Institution', 'Title', 'Abstract',
    'coIs_name', 'coIs_email'
]

# 4. Reindex to lock in those specific columns
final_noirlab = new_df.reindex(columns=target_columns)
final_noirlab['PI_Institution'] = final_noirlab['PI_email'].str.extract(r'@(.*)\.')
final_noirlab

,PropID,time TIME_CRITICAL,time NORMAL,Instrument,PI_name,PI_email,PI_Institution,Title,Abstract,coIs_name,coIs_email
0,2025B-366722,NaN,5.0,Goodman,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025B-589422,NaN,0.7,Goodman,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025B-886282,NaN,5.0,Goodman,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026B-607682,NaN,2.7,TripleSpec4.1,Swayamtrupta Panda,swayamtrupta.panda@noirlab.edu,noirlab,A NIR Spectroscopic Study of Bright AGN Backup...,The broad-line region (BLR) encodes the fundam...,"Anahis De la barra manzano, Yan-rong Li, Mary ...",ADELABARRA2020@udec.cl; liyanrong@mail.ihep.ac...
5,2026B-214372,NaN,1.0,TripleSpec4.1,"Anna O'grady, Sam Rose",aogrady@andrew.cmu.edu; srose@caltech.edu,andrew.cmu.edu; srose@caltech,Searching for super-AGB stars in the Magellani...,Super-asymptotic giant branch (SAGB) stars rep...,"Kaustav Das, Kishalay De, Maria Drout, Daichi ...",kdas@caltech.edu; kd3038@columbia.edu; maria.d...
6,2026B-174927,NaN,1.4,TripleSpec4.1,Benjamin Rackham,brackham@mit.edu,mit,Characterizing Cool Candidate Exoplanet Hosts ...,Planetary transits of cool dwarfs (T_eff < 390...,Adam Burgasser,aburgasser@ucsd.edu
7,2026B-987123,NaN,2.6,Goodman,Swayamtrupta Panda,swayamtrupta.panda@noirlab.edu,noirlab,Radio-mode AGN feedback caught in the act,We have selected a sample of 14 nearby radio g...,"Edi Bon, Miroslav Filipovic, Paola Marziani",edibon@gmail.com; M.Filipovic@westernsydney.ed...
9,2026B-819681,NaN,2.0,Goodman,"Christoffer Fremling, K-ryan Hinds",fremling@caltech.edu; khinds@caltech.edu,caltech.edu; khinds@caltech,Supporting Z+LIONS: ZTF+LSST Inventory Of Nucl...,The Vera Rubin Observatory's LSST will discove...,"Igor Andreoni, Ryan Chornock, Michael Coughlin...",igor.andreoni@unc.edu; chornock@berkeley.edu; ...
11,2026B-458833,NaN,1.1,Goodman,Lou baya Ould rouis,lbor@bu.edu,bu,Searching for the remnants of the most massive...,Intermediate-mass main sequence stars are diﬃc...,"Joseph Guidry, Jj Hermes",jaguidry@bu.edu; jjhermes@bu.edu
12,2026B-341708,NaN,1.6,Goodman,Nabeel Rehemtulla,nabeelr@u.northwestern.edu,u.northwestern,Surveying infant supernovae by automatically t...,Despite great advances in our understanding of...,"Igor Andreoni, Jonathan Carney, Michael Coughl...",igor.andreoni@unc.edu; jcarney@unc.edu; cough0...
14,2026B-942088,NaN,0.8,Goodman,Eric Bellm,ecbellm@uw.edu,uw,Characterizing the Accretion Disks of Compact ...,The Vera C. Rubin Observatory is now beginning...,"Poshak Gandhi, Rob Hynes, Liliana Rivera sandoval",poshak.gandhi@soton.ac.uk; rhynes@lsu.edu; lil...
16,2026B-532854,NaN,1.2,Goodman,Alice Townsend,a.townsend@bham.ac.uk,bham.ac,Spectroscopic Classification of Strongly Lense...,Strong gravitationally lensed supernovae are n...,"Suhail Dhawan, Ariel Goobar, Erin Hayes, Joel ...",s.dhawan@bham.ac.uk; ariel@fysik.su.se; eeh55@...
18,2026B-904429,NaN,0.7,Goodman,Chang Liu,ptg.cliu@u.northwestern.edu,u.northwestern,A Systematic Study of the Coolest Explosions,"Red, subluminous transients are one of the rem...","Georgios Dimitriadis, Saarah Hall, Lindsey Kwo...",g.dimitriadis@lancaster.ac.uk; saarah@u.northw...
20,2026B-731798,NaN,1.0,Goodman,Alexa Gordon,alexagordon2026@u.northwestern.edu,u.northwestern,Constructing a Complete Sample of Fast Radio B...,"Fast radio bursts (FRBs) are bright, milliseco...","Lucas Bernales, Manisha Caleb, Adam Deller, Yu...",lucas.bernales.c@mail.pucv.cl; manisha.caleb@s...
22,2026B-398365,NaN,1.5,Goodman,Michael Davis,davi4614@umn.edu,umn,Flux-limited characterization of GRBs and othe...,"We propose a flux-limited, duration-agnostic f...","Tomas Ahumada, Shreya Anand, Michael Coughlin,...",tomas.ahumada@noirlab.edu; sanand08@stanford.e...
24,2026B-352126,NaN,5.6,Goodman,Swayamtrupta Panda,swayamtrupta.panda@noirlab.edu,noirlab,Assessing the reliability of Single-Band Photo...,The reverberation mapping (RM) method measures...,Szymon Kozlowski,simkoz@astrouw.edu.pl
26,2026B-531718,NaN,1.0,Goodman,Haille Perkins,haillep2@illinois.edu,illinois,Exploring the Physics of Early-Times Rare Tran...,The imminent arrival of wide-field surveys lik...,"Henna Abunemeh, Katie Auchettl, Kyle Davis, Ka...",habun2@illinois.edu; katie.auchettl@unimelb.ed...
28,2026B-431664,NaN,0.9,Goodman,Jason Hinkle,jhinkle6@illinois.edu,illinois,Building an ANT-hill: SOAR/AEON Optical Spectr...,All massive galaxies host supermassive black h...,"Katie Auchettl, Athena Engholm, Decker French,...",katie.auchettl@unimelb.edu.au; engholm2@illino...
30,2026B-891013,NaN,2.0,Goodman,Konstantina Boutsia,konstantina.boutsia@noirlab.edu,noirlab,Populating the redshift desert,"Bright, high-z QSOs are of fundamental importa...","Giorgio Calderone, Stefano Cristiani, Andrea G...",giorgio.calderone@inaf.it; stefano.cristiani@i...

In [87]:
sum(final_noirlab['time NORMAL'])

37.8